### ISSUE TITLE
full version? 

### ISSUE THREAD

**Issue by peternara** [chengzhang/CRNN#1]
Hi, @chengzhang 
Is this a full version? test.py does not seem to exist.
thanks.

**Comment by chengzhang** [comment]
Yes, It's the full version.  It's available for training, validation, and test. test.py is designed to load a checkpoint and do the inference.

**Comment by peternara** [comment]
@chengzhang thank for rely.
hmm, I can not find your "test.py" file. Could you provide it? I want to prediction source file and exmaple command line.

**Comment by chengzhang** [comment]
The test.py is under construction. Sorry. I'll upload it as soon as I finish it. As to example command line, please take a look at train.sh and train.py. You can simply run 'sh ./train.sh' to execute example case. And all available args are defined in train.py.

**Comment by peternara** [comment]
@chengzhang thank for rely too.
I expect your full version. I will wait for it.:)
