### ISSUE TITLE
Robust Scene Text Recognition with Automatic Rectification

### ISSUE THREAD

**Issue by peternara** [chengzhang/CRNN#2]
Hi, @chengzhang 
* Is base paper "Robust Scene Text Recognition with Automatic Rectification" ?

**Comment by chengzhang** [comment]
Yes, it's one of the references. A 10-point affine transformation is used there. 
Another related work is "STAR-Net: A SpaTial Attention Residue Network for Scene Text Recognition", which involves a 6-point affine transformation.

**Comment by peternara** [comment]
@chengzhang thanks
I have implemented CRNN based. Then, I try to improve performance by using other algorithms.

**Comment by Lesley96-11** [comment]
@peternara  Do you improve the performance of CRNN, do you know how to achieve the result of  "Robust Scene Text Recognition with Automatic Rectification" ? I really want to know how to achieve, Thanks

**Comment by peternara** [comment]
@zxy3416391 
When I implemented CRNN with tf, we tried various tests to show similar performance to the paper. 
In fact,  was a bit less performance than the paper itself. :cry:  
Therefore, the STN was attached to the front part. so the performance was slightly higher than CRNN.
Currently, I am preparing my thesis through various experiments.
