### ISSUE TITLE
STN

### ISSUE THREAD

**Issue by wushilian** [chengzhang/CRNN#4]
你好，你的代码里是回归一个2*3的矩阵吧，而不是论文里的10个点？

**Comment by chengzhang** [comment]
@wushilian "Robust Scene Text Recognition with Automatic Rectification" 这篇文章用了10个点；"STAR-Net: A SpaTial Attention Residue Network for Scene Text Recognition"这篇文章用了6个点。你可以在这个基础上，尝试自己改一改~
